import { CategoryType } from "@/store/slices/categoriesReducer";
import { HardcodedRecipiesType } from "@/store/slices/hardcodedRecipeReducer";
import { RecipeType } from "@/store/slices/recipeReducer";

export const LANGUAGES = [
  { name: "English", id: 1 },
  { name: "Romanian", id: 2 },
];

export const CATEGORIES_DATA: CategoryType[] = [
  {
    name: "My recipies",
    image: require("../assets/food-categories/fish.jpg"),
    id: 1,
    selected: false,
  },
  {
    name: "Favorites",
    image: require("../assets/food-categories/favorites.png"),
    id: 2,
    selected: false,
  },
  {
    name: "Beef",
    image: require("../assets/food-categories/beef.png"),
    id: 3,
    selected: false,
  },
  {
    name: "Dessert",
    image: require("../assets/food-categories/dessert.webp"),
    id: 5,
    selected: false,
  },
  {
    name: "Chicken",
    image: require("../assets/food-categories/chicken.png"),
    id: 4,
    selected: false,
  },

  {
    name: "Lamb",
    image: require("../assets/food-categories/lamb.webp"),
    id: 6,
    selected: false,
  },
  {
    name: "Seafood",
    image: require("../assets/food-categories/sea-food.webp"),
    id: 7,
    selected: false,
  },
];
export type SelectedRecipeType = {
  name: string;
  image: any;
  id: number;
  categoryId: number;
  details: RecipeType;
};

export const HARDCODED_RECIPIES: HardcodedRecipiesType = {
  beef: {
    id: 100,
    name: "Beef",
    image: require("../assets/food-categories/beef.png"),
    categoryId: 3,
    data: [
      {
        name: "Beef",
        image: require("../assets/food-categories/beef.png"),
        id: 101,
        categoryId: 3,
        details: {
          id: 101,
          favorites: false,
          image: require("../assets/food-categories/beef.png"),
          title: "Beef dish",
          timeToCook: 30,
          servings: 4,
          description: "Beef dish",
          calories: 400,
          temperature: 100,
          ingredients: [
            "1kg Beef",
            "2 tbs Plain Flour",
            "1 tbs Salt",
            "1 tbs Pepper",
            "1 tbs Olive Oil",
            "1 tbs Onion",
            "1 tbs Garlic",
            "1 tbs Tomato Sauce",
            "1 tbs Tomato",
            "1 tbs Basil",
            "1 tbs Parsley",
            "1 tbs Oregano",
            "1 tbs Sugar",
          ],
        },
      },
      {
        name: "Beef",
        image: require("../assets/food-categories/beef2.png"),
        id: 102,
        categoryId: 3,
        details: {
          id: 102,
          favorites: false,
          image: require("../assets/food-categories/beef2.png"),
          title: "Beef with vegetables",
          description: "Beef with vegetables",
          timeToCook: 30,
          servings: 4,
          calories: 400,
          temperature: 100,
          ingredients: [
            "1kg Beef",
            "2 tbs Plain Flour",
            "1 tbs Salt",
            "1 tbs Pepper",
            "1 tbs Olive Oil",
            "1 tbs Onion",
            "1 tbs Garlic",
            "1 tbs Tomato Sauce",
            "1 tbs Tomato",
            "1 tbs Basil",
            "1 tbs Parsley",
            "1 tbs Oregano",
            "1 tbs Sugar",
          ],
        },
      },
      {
        name: "Beef",
        image: require("../assets/food-categories/beef3.png"),
        id: 103,
        categoryId: 3,
        details: {
          id: 103,
          favorites: false,
          image: require("../assets/food-categories/beef3.png"),
          title: "Fried beef",
          description: "Fried beef",
          timeToCook: 30,
          servings: 4,
          calories: 400,
          temperature: 100,
          ingredients: [
            "1kg Beef",
            "2 tbs Plain Flour",
            "1 tbs Salt",
            "1 tbs Pepper",
            "1 tbs Olive Oil",
            "1 tbs Onion",
            "1 tbs Garlic",
            "1 tbs Tomato Sauce",
            "1 tbs Tomato",
            "1 tbs Basil",
            "1 tbs Parsley",
            "1 tbs Oregano",
            "1 tbs Sugar",
          ],
        },
      },
      {
        name: "Beef",
        image: require("../assets/food-categories/beef.png"),
        id: 104,
        categoryId: 3,
        details: {
          id: 104,
          favorites: false,
          image: require("../assets/food-categories/beef.png"),
          title: "Beef with vegetables",
          description: "Beef dish",
          timeToCook: 45,
          servings: 4,
          calories: 400,
          temperature: 100,
          ingredients: [
            "1kg Beef",
            "2 tbs Plain Flour",
            "1 tbs Salt",
            "1 tbs Pepper",
            "1 tbs Olive Oil",
            "1 tbs Onion",
            "1 tbs Garlic",
            "1 tbs Tomato Sauce",
            "1 tbs Tomato",
            "1 tbs Basil",
            "1 tbs Parsley",
            "1 tbs Oregano",
            "1 tbs Sugar",
          ],
        },
      },
      {
        name: "Beef",
        image: require("../assets/food-categories/beef2.png"),
        id: 105,
        categoryId: 3,
        details: {
          id: 105,
          favorites: false,

          image: require("../assets/food-categories/beef2.png"),
          title: "Beef with vegetables",
          description: "Beef dish",
          timeToCook: 60,
          servings: 4,
          calories: 400,
          temperature: 100,
          ingredients: [
            "1kg Beef",
            "2 tbs Plain Flour",
            "1 tbs Salt",
            "1 tbs Pepper",
            "1 tbs Olive Oil",
            "1 tbs Onion",
            "1 tbs Garlic",
            "1 tbs Tomato Sauce",
            "1 tbs Tomato",
            "1 tbs Basil",
            "1 tbs Parsley",
            "1 tbs Oregano",
            "1 tbs Sugar",
          ],
        },
      },
      {
        name: "Beef",
        image: require("../assets/food-categories/beef2.png"),
        id: 106,
        categoryId: 3,
        details: {
          id: 106,
          favorites: false,
          image: require("../assets/food-categories/beef2.png"),
          title: "Beef with vegetables",
          description: "Beef dish",
          timeToCook: 70,
          servings: 4,
          calories: 400,
          temperature: 100,
          ingredients: [
            "1kg Beef",
            "2 tbs Plain Flour",
            "1 tbs Salt",
            "1 tbs Pepper",
            "1 tbs Olive Oil",
            "1 tbs Onion",
            "1 tbs Garlic",
            "1 tbs Tomato Sauce",
            "1 tbs Tomato",
            "1 tbs Basil",
            "1 tbs Parsley",
            "1 tbs Oregano",
            "1 tbs Sugar",
          ],
        },
      },
      {
        name: "Beef",
        image: require("../assets/food-categories/beef2.png"),
        id: 106,
        categoryId: 3,
        details: {
          id: 106,
          favorites: false,
          image: require("../assets/food-categories/beef2.png"),
          title: "Beef with vegetables",
          description: "Beef dish",
          timeToCook: 70,
          servings: 4,
          calories: 400,
          temperature: 100,
          ingredients: [
            "1kg Beef",
            "2 tbs Plain Flour",
            "1 tbs Salt",
            "1 tbs Pepper",
            "1 tbs Olive Oil",
            "1 tbs Onion",
            "1 tbs Garlic",
            "1 tbs Tomato Sauce",
            "1 tbs Tomato",
            "1 tbs Basil",
            "1 tbs Parsley",
            "1 tbs Oregano",
            "1 tbs Sugar",
          ],
        },
      },
      {
        name: "Beef",
        image: require("../assets/food-categories/beef2.png"),
        id: 106,
        categoryId: 3,
        details: {
          id: 106,
          favorites: false,
          image: require("../assets/food-categories/beef2.png"),
          title: "Beef with vegetables",
          description: "Beef dish",
          timeToCook: 70,
          servings: 4,
          calories: 400,
          temperature: 100,
          ingredients: [
            "1kg Beef",
            "2 tbs Plain Flour",
            "1 tbs Salt",
            "1 tbs Pepper",
            "1 tbs Olive Oil",
            "1 tbs Onion",
            "1 tbs Garlic",
            "1 tbs Tomato Sauce",
            "1 tbs Tomato",
            "1 tbs Basil",
            "1 tbs Parsley",
            "1 tbs Oregano",
            "1 tbs Sugar",
          ],
        },
      },
      {
        name: "Beef",
        image: require("../assets/food-categories/beef2.png"),
        id: 106,
        categoryId: 3,
        details: {
          id: 106,
          favorites: false,
          image: require("../assets/food-categories/beef2.png"),
          title: "Beef with vegetables",
          description: "Beef dish",
          timeToCook: 70,
          servings: 4,
          calories: 400,
          temperature: 100,
          ingredients: [
            "1kg Beef",
            "2 tbs Plain Flour",
            "1 tbs Salt",
            "1 tbs Pepper",
            "1 tbs Olive Oil",
            "1 tbs Onion",
            "1 tbs Garlic",
            "1 tbs Tomato Sauce",
            "1 tbs Tomato",
            "1 tbs Basil",
            "1 tbs Parsley",
            "1 tbs Oregano",
            "1 tbs Sugar",
          ],
        },
      },
      {
        name: "Beef",
        image: require("../assets/food-categories/beef2.png"),
        id: 106,
        categoryId: 3,
        details: {
          id: 106,
          favorites: false,
          image: require("../assets/food-categories/beef2.png"),
          title: "Beef with vegetables",
          description: "Beef dish",
          timeToCook: 70,
          servings: 4,
          calories: 400,
          temperature: 100,
          ingredients: [
            "1kg Beef",
            "2 tbs Plain Flour",
            "1 tbs Salt",
            "1 tbs Pepper",
            "1 tbs Olive Oil",
            "1 tbs Onion",
            "1 tbs Garlic",
            "1 tbs Tomato Sauce",
            "1 tbs Tomato",
            "1 tbs Basil",
            "1 tbs Parsley",
            "1 tbs Oregano",
            "1 tbs Sugar",
          ],
        },
      },
      {
        name: "Beef",
        image: require("../assets/food-categories/beef2.png"),
        id: 106,
        categoryId: 3,
        details: {
          id: 106,
          favorites: false,
          image: require("../assets/food-categories/beef2.png"),
          title: "Beef with vegetables",
          description: "Beef dish",
          timeToCook: 70,
          servings: 4,
          calories: 400,
          temperature: 100,
          ingredients: [
            "1kg Beef",
            "2 tbs Plain Flour",
            "1 tbs Salt",
            "1 tbs Pepper",
            "1 tbs Olive Oil",
            "1 tbs Onion",
            "1 tbs Garlic",
            "1 tbs Tomato Sauce",
            "1 tbs Tomato",
            "1 tbs Basil",
            "1 tbs Parsley",
            "1 tbs Oregano",
            "1 tbs Sugar",
          ],
        },
      },
      {
        name: "Beef",
        image: require("../assets/food-categories/beef2.png"),
        id: 106,
        categoryId: 3,
        details: {
          id: 106,
          favorites: false,
          image: require("../assets/food-categories/beef2.png"),
          title: "Beef with vegetables",
          description: "Beef dish",
          timeToCook: 70,
          servings: 4,
          calories: 400,
          temperature: 100,
          ingredients: [
            "1kg Beef",
            "2 tbs Plain Flour",
            "1 tbs Salt",
            "1 tbs Pepper",
            "1 tbs Olive Oil",
            "1 tbs Onion",
            "1 tbs Garlic",
            "1 tbs Tomato Sauce",
            "1 tbs Tomato",
            "1 tbs Basil",
            "1 tbs Parsley",
            "1 tbs Oregano",
            "1 tbs Sugar",
          ],
        },
      },
    ],
  },
  dessert: {
    name: "Dessert",
    image: require("../assets/food-categories/dessert.webp"),
    id: 200,
    categoryId: 5,
    data: [
      {
        name: "Dessert",
        image: require("../assets/food-categories/dessert.webp"),
        id: 201,
        categoryId: 5,
        details: {
          id: 201,
          favorites: false,
          image: require("../assets/food-categories/dessert.webp"),
          title: "Dessert cake",
          description: "Delicious Dessert Cake",
          timeToCook: 45,
          servings: 4,
          calories: 400,
          temperature: 100,
          ingredients: [
            "4 eggs",
            "2 tbs Plain Flour",
            "1 tbs Olive Oil",
            "1 tbs Sugar",
            "100g chocolate",
            "1 tbs vanilla extract",
            "1 tbs cocoa powder",
            "1 tbs baking powder",
            "1 tbs baking soda",
            "1 tbs salt",
          ],
        },
      },
      {
        name: "Dessert",
        image: require("../assets/food-categories/dessert2.webp"),
        id: 202,
        categoryId: 5,
        details: {
          id: 202,
          favorites: false,
          image: require("../assets/food-categories/dessert2.webp"),
          title: "Biscuits Chocolate",
          description: "Sweet Dessert",
          timeToCook: 15,
          servings: 6,
          calories: 1000,
          temperature: 100,
          ingredients: [
            "4 eggs",
            "2 tbs Plain Flour",
            "1 tbs Olive Oil",
            "1 tbs Sugar",
            "100g chocolate",
            "1 tbs vanilla extract",
            "1 tbs cocoa powder",
            "1 tbs baking powder",
            "1 tbs baking soda",
            "1 tbs salt",
          ],
        },
      },
      {
        name: "Dessert",
        image: require("../assets/food-categories/dessert3.png"),
        id: 203,
        categoryId: 5,
        details: {
          id: 203,
          favorites: false,
          image: require("../assets/food-categories/dessert3.png"),
          title: "Cheesecake",
          description: "Sweet Dessert",
          timeToCook: 120,
          servings: 3,
          calories: 1000,
          temperature: 100,
          ingredients: [
            "200g chocolate",
            "2 eggs",
            "2 tbs Plain Flour",
            "1 tbs Olive Oil",
            "1 tbs Sugar",
            "1 tbs vanilla extract",
            "1 tbs cocoa powder",
            "1 tbs baking powder",
            "1 tbs baking soda",
            "1 tbs salt",
          ],
        },
      },
      {
        name: "Dessert",
        image: require("../assets/food-categories/dessert2.webp"),
        id: 204,
        categoryId: 5,
        details: {
          id: 204,
          favorites: false,
          image: require("../assets/food-categories/dessert2.webp"),
          title: "Candy sweet chocolate",
          description: "Sweet Candy Dessert",
          timeToCook: 55,
          servings: 4,
          calories: 600,
          temperature: 100,
          ingredients: [
            "1 tbs Olive Oil",
            "4 eggs",
            "2 tbs Plain Flour",
            "1 tbs Sugar",
            "100g chocolate",
            "1 tbs vanilla extract",
            "1 tbs cocoa powder",
            "1 tbs baking powder",
            "1 tbs baking soda",
            "1 tbs salt",
          ],
        },
      },
      {
        name: "Dessert",
        image: require("../assets/food-categories/dessert3.png"),
        id: 205,
        categoryId: 5,
        details: {
          id: 205,
          favorites: false,
          image: require("../assets/food-categories/dessert3.png"),
          title: "Biscuits Chocolate",
          description: "Sweet Dessert",
          timeToCook: 66,
          servings: 6,
          calories: 1000,
          temperature: 100,
          ingredients: [
            "4 eggs",
            "2 tbs Plain Flour",
            "1 tbs Olive Oil",
            "1 tbs Sugar",
            "100g chocolate",
            "1 tbs vanilla extract",
            "1 tbs cocoa powder",
            "1 tbs baking powder",
            "1 tbs baking soda",
            "1 tbs salt",
          ],
        },
      },
      {
        name: "Dessert",
        image: require("../assets/food-categories/dessert.webp"),
        id: 206,
        categoryId: 5,
        details: {
          id: 206,
          favorites: false,
          image: require("../assets/food-categories/dessert.webp"),
          title: "Cheesecake",
          description: "Sweet Dessert",
          timeToCook: 45,
          servings: 6,
          calories: 1000,
          temperature: 100,
          ingredients: [
            "4 eggs",
            "2 tbs Plain Flour",
            "1 tbs Olive Oil",
            "1 tbs Sugar",
            "100g chocolate",
            "1 tbs vanilla extract",
            "1 tbs cocoa powder",
            "1 tbs baking powder",
            "1 tbs baking soda",
            "1 tbs salt",
          ],
        },
      },
    ],
  },
  chicken: {
    name: "Chicken",
    image: require("../assets/food-categories/dessert.webp"),
    id: 300,
    categoryId: 5,
    data: [
      {
        name: "Chicken",
        image: require("../assets/food-categories/chicken.png"),
        id: 301,
        categoryId: 5,
        details: {
          id: 301,
          favorites: false,
          image: require("../assets/food-categories/chicken.png"),
          title: "Chicken",
          description: "Delicious Chicken",
          timeToCook: 30,
          servings: 4,
          calories: 400,
          temperature: 100,
          ingredients: [
            "4 eggs",
            "2 tbs Plain Flour",
            "1 tbs Olive Oil",
            "1 tbs Sugar",
            "100g chocolate",
            "1 tbs vanilla extract",
            "1 tbs cocoa powder",
            "1 tbs baking powder",
            "1 tbs baking soda",
            "1 tbs salt",
          ],
        },
      },
    ],
  },
  lamb: {
    name: "Lamb",
    image: require("../assets/food-categories/lamb.webp"),
    id: 400,
    categoryId: 5,
    data: [
      {
        name: "Lamb",
        image: require("../assets/food-categories/lamb.webp"),
        id: 401,
        categoryId: 5,
        details: {
          id: 401,
          favorites: false,
          image: require("../assets/food-categories/lamb.webp"),
          title: "Lamb",
          description: "Delicious Lamb",
          timeToCook: 65,
          servings: 4,
          calories: 400,
          temperature: 100,
          ingredients: [
            "4 eggs",
            "2 tbs Plain Flour",
            "1 tbs Olive Oil",
            "1 tbs Sugar",
            "100g chocolate",
            "1 tbs vanilla extract",
            "1 tbs cocoa powder",
            "1 tbs baking powder",
            "1 tbs baking soda",
            "1 tbs salt",
          ],
        },
      },
    ],
  },
  seafood: {
    name: "Seafood",
    image: require("../assets/food-categories/sea-food.webp"),
    id: 500,
    categoryId: 5,
    data: [
      {
        name: "Seafood",
        image: require("../assets/food-categories/sea-food.webp"),
        id: 500,
        categoryId: 5,
        details: {
          id: 500,
          favorites: false,
          image: require("../assets/food-categories/sea-food.webp"),
          title: "Seafood",
          description: "Delicious Seafood",
          timeToCook: 20,
          servings: 4,
          calories: 400,
          temperature: 100,
          ingredients: [
            "4 eggs",
            "2 tbs Plain Flour",
            "1 tbs Olive Oil",
            "1 tbs Sugar",
            "100g chocolate",
            "1 tbs vanilla extract",
            "1 tbs cocoa powder",
            "1 tbs baking powder",
            "1 tbs baking soda",
            "1 tbs salt",
          ],
        },
      },
    ],
  },
};
