export const CATEGORIES = [
  {
    name: "My food",
    image: require("../assets/food-categories/fish.jpg"),
    id: 1,
  },
  {
    name: "My favorites",
    image: require("../assets/food-categories/favorites.png"),
    id: 2,
  },
  {
    name: "Beef",
    image: require("../assets/food-categories/beef.png"),
    id: 3,
  },
  {
    name: "Dessert",
    image: require("../assets/food-categories/dessert.webp"),
    id: 5,
  },
  {
    name: "Chicken",
    image: require("../assets/food-categories/chicken.png"),
    id: 4,
  },

  {
    name: "Lamb",
    image: require("../assets/food-categories/lamb.webp"),
    id: 6,
  },
  {
    name: "Seafood",
    image: require("../assets/food-categories/sea-food.webp"),
    id: 7,
  },
];

export type SelectedRecipeType = {
  name: string;
  image: any;
  id: number;
  categoryId: number;
  details: {
    image: any;
    title: string;
    subtitle: string;
    timeToCook: string;
    servings: number;
    calories: number;
    temperature: number;
    ingredients: string[];
  };
};

export type RecipeType = {
  name: string;
  image: any;
  id: number;
  categoryId: number;
  data?: {
    name: string;
    image: any;
    id: number;
    categoryId: number;
    details: {
      image: any;
      title: string;
      subtitle: string;
      timeToCook: string;
      servings: number;
      calories: number;
      temperature: number;
      ingredients: string[];
    };
  }[];
};
export const RECIPIES = {
  beef: {
    name: "Beef",
    image: require("../assets/food-categories/beef.png"),
    id: 10,
    categoryId: 3,
    data: [
      {
        name: "Beef dish",
        image: require("../assets/food-categories/beef.png"),
        id: 10,
        categoryId: 3,
        details: {
          image: require("../assets/food-categories/beef.png"),
          title: "Beef dish",
          subtitle: "Beef dish",
          timeToCook: "30 min",
          servings: 4,
          calories: 400,
          temperature: 100,
          ingredients: [
            "1kg Beef",
            "2 tbs Plain Flour",
            "1 tbs Salt",
            "1 tbs Pepper",
            "1 tbs Olive Oil",
            "1 tbs Onion",
            "1 tbs Garlic",
            "1 tbs Tomato Sauce",
            "1 tbs Tomato",
            "1 tbs Basil",
            "1 tbs Parsley",
            "1 tbs Oregano",
            "1 tbs Sugar",
          ],
        },
      },
      {
        name: "Beef with vegetables",
        image: require("../assets/food-categories/beef2.png"),
        id: 9,
        categoryId: 3,
        details: {
          image: require("../assets/food-categories/beef2.png"),
          title: "Beef with vegetables",
          subtitle: "Beef dish",
          timeToCook: "30 min",
          servings: 4,
          calories: 400,
          temperature: 100,
          ingredients: [
            "1kg Beef",
            "2 tbs Plain Flour",
            "1 tbs Salt",
            "1 tbs Pepper",
            "1 tbs Olive Oil",
            "1 tbs Onion",
            "1 tbs Garlic",
            "1 tbs Tomato Sauce",
            "1 tbs Tomato",
            "1 tbs Basil",
            "1 tbs Parsley",
            "1 tbs Oregano",
            "1 tbs Sugar",
          ],
        },
      },
      {
        name: "Fried beef",
        image: require("../assets/food-categories/beef3.png"),
        id: 11,
        categoryId: 3,
        details: {
          image: require("../assets/food-categories/beef3.png"),
          title: "Fried beef",
          subtitle: "Beef dish",
          timeToCook: "60 min",
          servings: 4,
          calories: 400,
          temperature: 100,
          ingredients: [
            "1kg Beef",
            "2 tbs Plain Flour",
            "1 tbs Salt",
            "1 tbs Pepper",
            "1 tbs Olive Oil",
            "1 tbs Onion",
            "1 tbs Garlic",
            "1 tbs Tomato Sauce",
            "1 tbs Tomato",
            "1 tbs Basil",
            "1 tbs Parsley",
            "1 tbs Oregano",
            "1 tbs Sugar",
          ],
        },
      },
      {
        name: "Beef with vegetables",
        image: require("../assets/food-categories/beef.png"),
        id: 9,
        categoryId: 3,
        details: {
          image: require("../assets/food-categories/beef.png"),
          title: "Beef with vegetables",
          subtitle: "Beef dish",
          timeToCook: "30 min",
          servings: 4,
          calories: 400,
          temperature: 100,
          ingredients: [
            "1kg Beef",
            "2 tbs Plain Flour",
            "1 tbs Salt",
            "1 tbs Pepper",
            "1 tbs Olive Oil",
            "1 tbs Onion",
            "1 tbs Garlic",
            "1 tbs Tomato Sauce",
            "1 tbs Tomato",
            "1 tbs Basil",
            "1 tbs Parsley",
            "1 tbs Oregano",
            "1 tbs Sugar",
          ],
        },
      },
      {
        name: "Beef with vegetables",
        image: require("../assets/food-categories/beef2.png"),
        id: 9,
        categoryId: 3,
        details: {
          image: require("../assets/food-categories/beef2.png"),
          title: "Beef with vegetables",
          subtitle: "Beef dish",
          timeToCook: "30 min",
          servings: 4,
          calories: 400,
          temperature: 100,
          ingredients: [
            "1kg Beef",
            "2 tbs Plain Flour",
            "1 tbs Salt",
            "1 tbs Pepper",
            "1 tbs Olive Oil",
            "1 tbs Onion",
            "1 tbs Garlic",
            "1 tbs Tomato Sauce",
            "1 tbs Tomato",
            "1 tbs Basil",
            "1 tbs Parsley",
            "1 tbs Oregano",
            "1 tbs Sugar",
          ],
        },
      },
      {
        name: "Beef with vegetables",
        image: require("../assets/food-categories/beef2.png"),
        id: 9,
        categoryId: 3,
        details: {
          image: require("../assets/food-categories/beef2.png"),
          title: "Beef with vegetables",
          subtitle: "Beef dish",
          timeToCook: "30 min",
          servings: 4,
          calories: 400,
          temperature: 100,
          ingredients: [
            "1kg Beef",
            "2 tbs Plain Flour",
            "1 tbs Salt",
            "1 tbs Pepper",
            "1 tbs Olive Oil",
            "1 tbs Onion",
            "1 tbs Garlic",
            "1 tbs Tomato Sauce",
            "1 tbs Tomato",
            "1 tbs Basil",
            "1 tbs Parsley",
            "1 tbs Oregano",
            "1 tbs Sugar",
          ],
        },
      },
    ],
  },
  dessert: {
    name: "Dessert",
    image: require("../assets/food-categories/dessert.webp"),
    id: 12,
    categoryId: 5,
    data: [
      {
        name: "Dessert cake",
        image: require("../assets/food-categories/dessert.webp"),
        id: 12,
        categoryId: 5,
        details: {
          image: require("../assets/food-categories/dessert.webp"),
          title: "Dessert cake",
          subtitle: "Delicious Dessert Cake",
          timeToCook: "30 min",
          servings: 4,
          calories: 400,
          temperature: 100,
          ingredients: [
            "4 eggs",
            "2 tbs Plain Flour",
            "1 tbs Olive Oil",
            "1 tbs Sugar",
            "100g chocolate",
            "1 tbs vanilla extract",
            "1 tbs cocoa powder",
            "1 tbs baking powder",
            "1 tbs baking soda",
            "1 tbs salt",
          ],
        },
      },
      {
        name: "Biscuits Chocolate",
        image: require("../assets/food-categories/dessert2.webp"),
        id: 9,
        categoryId: 5,
        details: {
          image: require("../assets/food-categories/dessert2.webp"),
          title: "Biscuits Chocolate",
          subtitle: "Sweet Dessert",
          timeToCook: "45 min",
          servings: 6,
          calories: 1000,
          temperature: 100,
          ingredients: [
            "4 eggs",
            "2 tbs Plain Flour",
            "1 tbs Olive Oil",
            "1 tbs Sugar",
            "100g chocolate",
            "1 tbs vanilla extract",
            "1 tbs cocoa powder",
            "1 tbs baking powder",
            "1 tbs baking soda",
            "1 tbs salt",
          ],
        },
      },
      {
        name: "Cheesecake",
        image: require("../assets/food-categories/dessert3.png"),
        id: 10,
        categoryId: 5,
        details: {
          image: require("../assets/food-categories/dessert3.png"),
          title: "Cheesecake",
          subtitle: "Sweet Dessert",
          timeToCook: "60 min",
          servings: 3,
          calories: 1000,
          temperature: 100,
          ingredients: [
            "200g chocolate",
            "2 eggs",
            "2 tbs Plain Flour",
            "1 tbs Olive Oil",
            "1 tbs Sugar",
            "1 tbs vanilla extract",
            "1 tbs cocoa powder",
            "1 tbs baking powder",
            "1 tbs baking soda",
            "1 tbs salt",
          ],
        },
      },
      {
        name: "Candy sweet chocolate",
        image: require("../assets/food-categories/dessert2.webp"),
        id: 11,
        categoryId: 5,
        details: {
          image: require("../assets/food-categories/dessert2.webp"),
          title: "Candy sweet chocolate",
          subtitle: "Sweet Candy Dessert",
          timeToCook: "35 min",
          servings: 4,
          calories: 600,
          temperature: 100,
          ingredients: [
            "1 tbs Olive Oil",
            "4 eggs",
            "2 tbs Plain Flour",
            "1 tbs Sugar",
            "100g chocolate",
            "1 tbs vanilla extract",
            "1 tbs cocoa powder",
            "1 tbs baking powder",
            "1 tbs baking soda",
            "1 tbs salt",
          ],
        },
      },
      {
        name: "Biscuits Chocolate",
        image: require("../assets/food-categories/dessert3.png"),
        id: 13,
        categoryId: 5,
        details: {
          image: require("../assets/food-categories/dessert3.png"),
          title: "Biscuits Chocolate",
          subtitle: "Sweet Dessert",
          timeToCook: "45 min",
          servings: 6,
          calories: 1000,
          temperature: 100,
          ingredients: [
            "4 eggs",
            "2 tbs Plain Flour",
            "1 tbs Olive Oil",
            "1 tbs Sugar",
            "100g chocolate",
            "1 tbs vanilla extract",
            "1 tbs cocoa powder",
            "1 tbs baking powder",
            "1 tbs baking soda",
            "1 tbs salt",
          ],
        },
      },
      {
        name: "Cheesecake",
        image: require("../assets/food-categories/dessert.webp"),
        id: 14,
        categoryId: 5,
        details: {
          image: require("../assets/food-categories/dessert.webp"),
          title: "Cheesecake",
          subtitle: "Sweet Dessert",
          timeToCook: "45 min",
          servings: 6,
          calories: 1000,
          temperature: 100,
          ingredients: [
            "4 eggs",
            "2 tbs Plain Flour",
            "1 tbs Olive Oil",
            "1 tbs Sugar",
            "100g chocolate",
            "1 tbs vanilla extract",
            "1 tbs cocoa powder",
            "1 tbs baking powder",
            "1 tbs baking soda",
            "1 tbs salt",
          ],
        },
      },
    ],
  },
  chicken: {
    name: "Dessert",
    image: require("../assets/food-categories/dessert.webp"),
    id: 12,
    categoryId: 5,
    data: [
      {
        name: "Chicken",
        image: require("../assets/food-categories/chicken.png"),
        id: 12,
        categoryId: 5,
        details: {
          image: require("../assets/food-categories/chicken.png"),
          title: "Chicken",
          subtitle: "Delicious Chicken",
          timeToCook: "30 min",
          servings: 4,
          calories: 400,
          temperature: 100,
          ingredients: [
            "4 eggs",
            "2 tbs Plain Flour",
            "1 tbs Olive Oil",
            "1 tbs Sugar",
            "100g chocolate",
            "1 tbs vanilla extract",
            "1 tbs cocoa powder",
            "1 tbs baking powder",
            "1 tbs baking soda",
            "1 tbs salt",
          ],
        },
      },
    ],
  },
  lamb: {
    name: "Lamb",
    image: require("../assets/food-categories/lamb.webp"),
    id: 12,
    categoryId: 5,
    data: [
      {
        name: "Lamb",
        image: require("../assets/food-categories/lamb.webp"),
        id: 12,
        categoryId: 5,
        details: {
          image: require("../assets/food-categories/lamb.webp"),
          title: "Lamb",
          subtitle: "Delicious Lamb",
          timeToCook: "30 min",
          servings: 4,
          calories: 400,
          temperature: 100,
          ingredients: [
            "4 eggs",
            "2 tbs Plain Flour",
            "1 tbs Olive Oil",
            "1 tbs Sugar",
            "100g chocolate",
            "1 tbs vanilla extract",
            "1 tbs cocoa powder",
            "1 tbs baking powder",
            "1 tbs baking soda",
            "1 tbs salt",
          ],
        },
      },
    ],
  },
  seafood: {
    name: "Seafood",
    image: require("../assets/food-categories/sea-food.webp"),
    id: 12,
    categoryId: 5,
    data: [
      {
        name: "Seafood",
        image: require("../assets/food-categories/sea-food.webp"),
        id: 12,
        categoryId: 5,
        details: {
          image: require("../assets/food-categories/sea-food.webp"),
          title: "Seafood",
          subtitle: "Delicious Seafood",
          timeToCook: "30 min",
          servings: 4,
          calories: 400,
          temperature: 100,
          ingredients: [
            "4 eggs",
            "2 tbs Plain Flour",
            "1 tbs Olive Oil",
            "1 tbs Sugar",
            "100g chocolate",
            "1 tbs vanilla extract",
            "1 tbs cocoa powder",
            "1 tbs baking powder",
            "1 tbs baking soda",
            "1 tbs salt",
          ],
        },
      },
    ],
  },
};
